spring:
  profiles:
    active: prod
  mail:
    host: smtp.gmail.com
    port: 587
    username: sogongja0@gmail.com
    password: dqmrjdymsqsmehnu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 900MB
    
  cache:
    type: none



  thymeleaf:
    mode: HTML5
    cache: false
    
  web:
    resources:
      chain:
        strategy:
          fixed:
            enabled: true
   
server:
  servlet:
    session:
      timeout: 120m
      cookie:
        name: SOGONGJA_USER_JSESSIONID
    encoding:
      charset: UTF-8
      force: true
  error:
    whitelabel:
      enabled: false
    
system:
  slack-bot-url: https://hooks.slack.com/services/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
  slack-bot-channel-url: https://hooks.slack.com/services/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
  api-key: UE110X25S8Z6mmc4EEk1Ag==
  version: 202104071900
    
---
    
spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: detect
  primary:
    datasource:
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3307/sogongja?useUnicode=yes&characterEncoding=UTF-8
      username: root
      password: thvmxmfoqtm
      #jdbc-url: jdbc:log4jdbc:mariadb://sogongja-aurora-prod-instance.cluster-cyoshxr7pnby.ap-northeast-2.rds.amazonaws.com:3306/sogongja?useUnicode=yes&characterEncoding=UTF-8
      #username: admin
      #password: thrhdwk5834#

system:
  slack-send: false
  upload-file-path: D:\SOGONGJA\upload
  thumbnail-file-path: D:\SOGONGJA\upload\thumb
    
server:
  port: 2082

logging:
  file: 
    max-history: 20
    max-size: 10MB
    name: logs/logback.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
#    file: "%d %-5level [%thread] %logger : %msg%n" 
  level:
    root: info
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
      connection: off
    org:
      thymeleaf: off

app:
  ########### KAKAO
  kakao-client-id: ca030a4f9bf9d299095948d15d0982d2
  kakao-request-token-uri: https://kauth.kakao.com/oauth/authorize
  kakao-access-token-uri: https://kauth.kakao.com/oauth/token
  kakao-api-uri: https://kapi.kakao.com/v2
  ########### GOOGLE
  google-client-id: 962520289844-hgpq28i60v460goj8qapo3vrao72qrnv.apps.googleusercontent.com
  google-client-secret: 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
  google-request-token-uri: https://accounts.google.com/o/oauth2/v2/auth
  google-access-token-uri: https://oauth2.googleapis.com/token
  google-api-uri: https://www.googleapis.com/oauth2/v3
  ########### NAVER
  naver-client-id: ejTOG6FfjN38pu8Tcsf3
  naver-client-secret: bj_jZTZU0v
  naver-request-token-uri: https://nid.naver.com/oauth2.0/authorize
  naver-access-token-uri: https://nid.naver.com/oauth2.0/token
  naver-api-uri: https://openapi.naver.com/v1
  host: http://localhost:2082
  emailAddress: sogongja0@gmail.com
  ########### JWT
  jwt-secret: soogoongjaa
  jwt-limit: 604800000

---

spring:
  config:
    activate:
      on-profile: dev
  primary:
    datasource:
      jdbc-url: jdbc:log4jdbc:mariadb://nfm.stoneitgt.com:3306/sogongja?useUnicode=yes&characterEncoding=UTF-8
      username: sogongja
      password: sogongja@2021!
      
system:
  slack-send: false
  upload-file-path: /www/sogongja/upload
  thumbnail-file-path: /www/sogongja/upload/thumb

server:
  port: 12082
  servlet:
    context-path: /sogongja

logging:
  file: 
    max-history: 20
    max-size: 10MB
    name: /www/sogongja/logs/user/logback.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    root: info
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
      connection: off
    org:
      thymeleaf: off
    
---

spring:
  config:
    activate:
      on-profile: prod
  primary:
    datasource:
#      jdbc-url: jdbc:log4jdbc:mariadb://121.254.171.155:3306/sogongja?useUnicode=yes&characterEncoding=UTF-8
#      username: sogongja
#      password: sogongja@2021!
      jdbc-url: jdbc:log4jdbc:mariadb://sogongja-aurora-prod-instance.cluster-cyoshxr7pnby.ap-northeast-2.rds.amazonaws.com:3306/sogongja?useUnicode=yes&characterEncoding=UTF-8
      username: admin
      password: thrhdwk5834#
      
system:
  slack-send: false
  #upload-file-path: /mnt/extra02/home/sogongja/upload
  #thumbnail-file-path: /mnt/extra02/home/sogongja/upload/thumb
  upload-file-path: /home/sogongja/sogongja-master/upload
  thumbnail-file-path: /home/sogongja/sogongja-master/upload/thumb
  
server:
  port: 2082
  undertow:
    accesslog:
      enabled: true
      dir: /app/logs/user

logging:
  file: 
    max-history: 180
    max-size: 10MB
    name: /app/logs/user/logback.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    root: info
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
      connection: off
    org:
      thymeleaf: off

app:
  ########### KAKAO
  kakao-client-id: ca030a4f9bf9d299095948d15d0982d2
  kakao-request-token-uri: https://kauth.kakao.com/oauth/authorize
  kakao-access-token-uri: https://kauth.kakao.com/oauth/token
  kakao-api-uri: https://kapi.kakao.com/v2
  ########### GOOGLE
  google-client-id: 962520289844-hgpq28i60v460goj8qapo3vrao72qrnv.apps.googleusercontent.com
  google-client-secret: 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
  google-request-token-uri: https://accounts.google.com/o/oauth2/v2/auth
  google-access-token-uri: https://oauth2.googleapis.com/token
  google-api-uri: https://www.googleapis.com/oauth2/v3
  ########### NAVER
  naver-client-id: ejTOG6FfjN38pu8Tcsf3
  naver-client-secret: bj_jZTZU0v
  naver-request-token-uri: https://nid.naver.com/oauth2.0/authorize
  naver-access-token-uri: https://nid.naver.com/oauth2.0/token
  naver-api-uri: https://openapi.naver.com/v1
  host: https://sogongja.co.kr
  emailAddress: sogongja0@gmail.com
  ########### JWT
  jwt-secret: soogoongjaa
  jwt-limit: 604800000